### ISSUE TITLE
[BUG ]Can't get the code editor widget

### ISSUE THREAD

**Issue by rohankishore** [smathot/pyqode.core#19]
This's the error im facing.

```Traceback (most recent call last):
  File "C:\Users\rohan\PycharmProjects\AuraText QT\AT.py", line 250, in <module>
    run()
  File "C:\Users\rohan\PycharmProjects\AuraText QT\AT.py", line 246, in run
    GUI = Window()
  File "C:\Users\rohan\PycharmProjects\AuraText QT\AT.py", line 94, in __init__
    self.current_editor = self.create_editor()
  File "C:\Users\rohan\PycharmProjects\AuraText QT\AT.py", line 178, in create_editor
    text_editor = api.CodeEdit()
  File "C:\Python\lib\site-packages\pyqode\core\api\code_edit.py", line 510, in __init__
    self.setLineWrapMode(self.NoWrap)
AttributeError: 'CodeEdit' object has no attribute 'NoWrap'

Process finished with exit code 1
```

**Comment by rohankishore** [comment]
Wow, still no resolution. Anyways I'm using QScintilla now so yeah I'm closing the issue.
